name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Tezos Node Docker image
      run: docker build docker-tezos-node --file docker-tezos-node/Dockerfile --tag tezos-node:$(date +%s)
